### ISSUE TITLE
generate_baseline.py crash with custom baselines

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#210]
```rmg2@PN130628 macos_security % ./scripts/generate_baseline.py -k arm64                    
Traceback (most recent call last):
  File "/Users/rmg2/Documents/GitHub/macos_security/./scripts/generate_baseline.py", line 564, in <module>
    main()
  File "/Users/rmg2/Documents/GitHub/macos_security/./scripts/generate_baseline.py", line 529, in main
    if mscp_data_yaml['authors'][args.keyword]:
KeyError: 'arm64'
rmg2@PN130628 macos_security % ```

**Comment by pnkelley** [comment]
I get a similar error when trying to generate a the script with the provided baselines as well.

`Traceback (most recent call last):
  File "/Users/pnkelley/Downloads/macos_security-monterey/./scripts/generate_guidance.py", line 7, in <module>
    import xlwt
ModuleNotFoundError: No module named 'xlwt'`

**Comment by robertgendler** [comment]
@pnkelley have you installed the required modules? 
https://github.com/usnistgov/macos_security/wiki/Getting-Started

`pip3 install -r requirements.txt --user`

That error means the python3 module is not installed.
